
#pragma once

// RGB Matrix Settings
#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_STARTUP_HUE 35
#define RGB_MATRIX_STARTUP_SAT 40
#define RGB_MATRIX_STARTUP_VAL 102
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#endif